import type { Metadata } from "next";
import { jost, inter } from "@/lib/fonts";
import "@/styles/global.css";
import { ViewTransitions } from "next-view-transitions";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ViewTransitions>
            <html
                lang="en"
                className={`${inter.variable} ${jost.variable} h-full antialiased`}
            >
                <body className="min-h-full flex flex-col">
                    <TooltipProvider>{children}</TooltipProvider>
                </body>
            </html>
        </ViewTransitions>
    );
}
